### ISSUE TITLE
After closing address bar, reclicking parcel should display address again

### ISSUE THREAD

**Issue by juancatothe** [CityOfDetroit/canvas#48]

**Comment by mikefresh** [comment]
I think this might be solved now? Im unable to recreate.

**Comment by juancatothe** [comment]
@mikefresh I've been looking into this, but could use your help.

Steps to recreate: 
-Click a building
-Swipe the address down
-Click any building, nothing will show up

**Comment by mikefresh** [comment]
Duplicate of #60
