### ISSUE TITLE
Hookup search bar to buildings

### ISSUE THREAD

**Issue by mikefresh** [CityOfDetroit/canvas#53]

**Comment by jmcbroom** [comment]
This is actually kind of tricky.

Traditionally we can send the search input to the geocoder and then it directly returns a geometry and parcel ID.

So to do this, there's a couple options:

- rebuild the geocoder to use the Building ID as the user-defined return value (for some dumb reason there can only be one)
- add a second `fetch()` to go grab the correct building based on the returned Parcel ID

the lazy option is to leave it as is until we can bring our base units into the GraphQL server: then we can geocode an address & get back all the parcel and building information in one go

**Comment by jmcbroom** [comment]
solved it using this strategy:

add a second fetch() to go grab the correct building based on the returned Parcel ID
