### ISSUE TITLE
Higher Color Contrast for Group Quarters

### ISSUE THREAD

**Issue by juancatothe** [CityOfDetroit/canvas#59]
Hard from a lower zoom level to differentiate between the green used for <strike>group quarters</strike> multi-unit and the purple used for residential.

**Comment by jmcbroom** [comment]
We can adjust these here: 
https://github.com/CityOfDetroit/canvas/blob/develop/src/components/Map/mapStyle.json#L3491

build_type of `81` is single-family home; `82` and `83` are multifamily. The documentation with this data dictionary is here: https://maps.semcog.org/BuildingFootprints/BuildingsDocumentation071916.pdf

**Comment by mikefresh** [comment]
Awesome sauce. However the group quarters should be coming from another feature service, not the semcog build_type. (should be in there already, ill look it up)

**Comment by juancatothe** [comment]
Edited

**Comment by mikefresh** [comment]
Whoops, nope! The only colors on the map should be orange and blue, Orange is GQ buildings, and they should go blue once surveyed. There should be no other color coded buildings besides whatever shading is applied by default to all footprints.

**Comment by juancatothe** [comment]
Closing issue per Mike's latest comment.
